# Data Preprocessing for JIT Bug Prediction

## Objective

The purpose of this notebook is to prepare the ApacheJIT dataset
for machine learning experiments.

The preprocessing pipeline includes:

- Data loading
- Target variable conversion
- Chronological ordering
- Feature selection
- Missing value handling
- Saving a clean processed dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
path = "/content/drive/MyDrive/JIT_bug_prediction/data/apachejit.csv"

df = pd.read_csv(path)

df.head()

,commit_id,project,buggy,fix,year,author_date,la,ld,nf,nd,ns,ent,ndev,age,nuc,aexp,arexp,asexp
0,7b8480744ea6e6fb41efd4329bb470c8f3c763db,apache/groovy,False,False,2003,1070355653,372,23,8,3,3,2.669743,0.250000,3.625000,2.125,243,243.0,0.683585
1,192b631e7be302ecde822546ba70a9853ddbda01,apache/groovy,False,False,2003,1063298262,2,2,2,2,1,1.000000,1.000000,0.000000,2.500,19,19.0,14.000000
2,0ab6465a7dece117c61c3efd3ec95d20524bdad6,apache/groovy,False,False,2003,1069704572,41,26,3,3,2,1.237612,0.666667,5.333333,45.000,233,233.0,0.000606
3,449241d5fa1aeadd5eb9fa1280d4104dc0dfb891,apache/groovy,False,False,2003,1068487625,8,6,2,1,1,0.591673,1.000000,3.000000,35.500,64,64.0,55.000000
4,698df9f5b0816e05bbf97a390428f8ef94e0cdbf,apache/groovy,False,False,2003,1063313516,70,4,6,3,1,2.519672,0.333333,0.000000,6.000,27,27.0,22.000000

In [4]:
print("Dataset Shape:", df.shape)

Dataset Shape: (106674, 18)

## Target Variable Conversion

The target variable `buggy` is converted into binary format.

0 → Non-Buggy Commit

1 → Buggy Commit

In [5]:
df['buggy'] = (
    df['buggy']
    .astype(str)
    .str.lower()
    .map({
        'false':0,
        'true':1
    })
)

In [6]:
df['buggy'].value_counts()

buggy
0    78435
1    28239
Name: count, dtype: int64

## Chronological Ordering

The dataset is sorted using author_date.

This preserves temporal order and enables
realistic future commit prediction.

In [7]:
df = df.sort_values(
    by='author_date'
)

df.head()

,commit_id,project,buggy,fix,year,author_date,la,ld,nf,nd,ns,ent,ndev,age,nuc,aexp,arexp,asexp
11,a322a829a586cf03685152f06cc7025d66062202,apache/groovy,0,False,2003,1063292086,58,0,1,1,1,0.0,1.0,0.0,1.0,10,10.0,6.0
39,8169b159895f5f727287f6dff351e61569d03f48,apache/groovy,0,False,2003,1063292137,78,0,1,1,1,0.0,0.0,0.0,0.0,21,21.0,1.0
118,a93ff66772451264ef054ed19e98448d3f01953b,apache/groovy,0,False,2003,1063292285,2,3,1,1,1,0.0,2.0,0.0,2.0,11,11.0,7.0
199,fae44a3dbc26273587a40250d4fa94ff8b2c22a9,apache/groovy,0,False,2003,1063292362,2,0,1,1,1,0.0,2.0,0.0,3.0,12,12.0,8.0
206,87578c39d8d55b8eab63b497391eed80b50120f4,apache/groovy,0,False,2003,1063292625,33,0,1,1,1,0.0,1.0,0.0,1.0,13,13.0,9.0

## Feature Selection

The selected features are commonly used
JIT software metrics.

In [8]:
selected_columns = [

    'author_date',

    'la',
    'ld',
    'nf',
    'nd',
    'ns',
    'ent',
    'ndev',
    'age',
    'nuc',
    'aexp',
    'arexp',
    'asexp',

    'buggy'
]

In [9]:
processed_df = df[selected_columns]

In [10]:
processed_df = processed_df.fillna(0)

In [11]:
processed_df.isnull().sum()

author_date    0
la             0
ld             0
nf             0
nd             0
ns             0
ent            0
ndev           0
age            0
nuc            0
aexp           0
arexp          0
asexp          0
buggy          0
dtype: int64

In [12]:
processed_df.head()

,author_date,la,ld,nf,nd,ns,ent,ndev,age,nuc,aexp,arexp,asexp,buggy
11,1063292086,58,0,1,1,1,0.0,1.0,0.0,1.0,10,10.0,6.0,0
39,1063292137,78,0,1,1,1,0.0,0.0,0.0,0.0,21,21.0,1.0,0
118,1063292285,2,3,1,1,1,0.0,2.0,0.0,2.0,11,11.0,7.0,0
199,1063292362,2,0,1,1,1,0.0,2.0,0.0,3.0,12,12.0,8.0,0
206,1063292625,33,0,1,1,1,0.0,1.0,0.0,1.0,13,13.0,9.0,0

## Saving Processed Dataset

The cleaned dataset is saved for use
in all future machine learning experiments.

In [13]:
processed_path = "/content/drive/MyDrive/JIT_bug_prediction/data/processed_data.csv"

processed_df.to_csv(
    processed_path,
    index=False
)

print("Saved Successfully")

Saved Successfully

In [14]:
processed_df.shape

(106674, 14)